CREATE EXTENSION IF NOT EXISTS citext;

CREATE TYPE user_role AS ENUM ('employer', 'employee'); 

CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
    email CITEXT UNIQUE NOT NULL,
    first_name VARCHAR(255) NOT NULL, 
    last_name VARCHAR(255) NOT NULL,
    role user_role NOT NULL,  
    created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(), 
    updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW()
);
